development:
  provider:
    repository_name: 'Commonwealth OAI Provider Development'
    respository_url: 'http://localhost:3000/catalog/oai'
    record_prefix: 'oai:dc3dev.bpl.org'
    admin_email: 'dev@localhost'
    sample_id: 'bpl-dev:abc123456'
  document:
    limit: 25
    set_fields:
      - label: 'oai_ark_id'
        solr_field: 'collection_ark_id_ssim'
test:
  provider:
    repository_name: 'Commonwealth OAI Provider Test'
    respository_url: 'http://localhost:3000/catalog/oai'
    record_prefix: 'oai:dc3dev.bpl.org'
    admin_email: 'test@localhost'
    sample_id: 'bpl-dev:abc123456'
  document:
    limit: 5
    set_fields:
      - label: 'oai_ark_id'
        solr_field: 'collection_ark_id_ssim'

staging:
  provider:
    repository_name: 'Commonwealth OAI =Connectict= Provider Staging'
    respository_url: 'https://oai-dc3dev.bpl.org/catalog/oai'
    record_prefix: 'oai:dc3dev.bpl.org'
    admin_email: 'staging@localhost'
    sample_id: 'bpl-dev:abc123456'
  document:
    limit: 250
    set_fields:
      - label: 'oai_ark_id'
        solr_field: 'collection_ark_id_ssim'

production:
  provider:
    repository_name: 'Commonwealth OAI Provider Production'
    respository_url: 'https://oai.digitalcommonwealth.org/catalog/oai'
    record_prefix: 'oai:digitalcommonwealth.org'
    admin_email: 'admin@digitalcommonwealth.org'
    sample_id: 'commonwealth:abc123456'
  document:
    limit: 250
    set_fields:
      - label: 'oai_ark_id'
        solr_field: 'collection_ark_id_ssim'
