load_defaults: 7.25.3

default: &default
  adapter: solr

development:
  <<: *default
  url: <%= ENV.fetch('SOLR_URL') { 'http://127.0.0.1:8983/solr/commonwealth_oai_dev' } %>

test: &test
  <<: *default
  url: <%= ENV.fetch('SOLR_URL') { 'http://127.0.0.1:8983/solr/commonwealth_oai_test' } %>

staging:
  <<: *default
  url: <%= Rails.application.credentials.dig(:solr, :url) %>

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:solr, :url) %>
