load_defaults: 7.25.3

default: &default
  adapter: solr

development:
  <<: *default
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>

test: &test
  <<: *default
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>

staging:
  <<: *default
  url: <%= Rails.application.credentials.dig(:solr, :url) %>

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:solr, :url) %>
